// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDogXZT-JjS2Ngzd3RLGQzJsWDO9xfSkUA',
    appId: '1:193230356724:web:6bb4edc569192210385ea1',
    messagingSenderId: '193230356724',
    projectId: 'guardian-safety-44fed',
    authDomain: 'guardian-safety-44fed.firebaseapp.com',
    storageBucket: 'guardian-safety-44fed.firebasestorage.app',
    measurementId: 'G-CSGN6V0GV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZYsCazuQPeiFGZRqd1w0D_Pt-KHeocYA',
    appId: '1:193230356724:android:a97ba7ce62622528385ea1',
    messagingSenderId: '193230356724',
    projectId: 'guardian-safety-44fed',
    storageBucket: 'guardian-safety-44fed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQQTb198eKTsDt9EJj3QHtr9wEvk33ffA',
    appId: '1:193230356724:ios:7bcf09de25ada494385ea1',
    messagingSenderId: '193230356724',
    projectId: 'guardian-safety-44fed',
    storageBucket: 'guardian-safety-44fed.firebasestorage.app',
    iosBundleId: 'com.example.guardianApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQQTb198eKTsDt9EJj3QHtr9wEvk33ffA',
    appId: '1:193230356724:ios:7bcf09de25ada494385ea1',
    messagingSenderId: '193230356724',
    projectId: 'guardian-safety-44fed',
    storageBucket: 'guardian-safety-44fed.firebasestorage.app',
    iosBundleId: 'com.example.guardianApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDogXZT-JjS2Ngzd3RLGQzJsWDO9xfSkUA',
    appId: '1:193230356724:web:acf53454feb748ce385ea1',
    messagingSenderId: '193230356724',
    projectId: 'guardian-safety-44fed',
    authDomain: 'guardian-safety-44fed.firebaseapp.com',
    storageBucket: 'guardian-safety-44fed.firebasestorage.app',
    measurementId: 'G-NP8XPMDMCR',
  );
}
